all: infixToPostfixTest

HEADER = ../ListBaseStack/ListBaseStack.hpp ExpressionConverter.hpp postfixCalculator.hpp

infixToPostfixTest: infixToPostfixTest.cpp $(HEADER)
	g++ -o infixToPostfixTest infixToPostfixTest.cpp
