all: ExpressionTreeMain

# header files
HEADER = ExpressionTree.hpp ../BinaryTree/BinaryTree.hpp ../../03_Stack/calculator/ExpressionConverter.hpp ../../03_Stack/ListBaseStack/ListBaseStack.hpp

ExpressionTreeMain: ExpressionTreeMain.cpp $(HEADER)
	g++ -o ExpressionTreeMain ExpressionTreeMain.cpp
