all: listTestApp listADT

# header files
HEADER = ArrayList/ArrayList.hpp SinglyLinkedList/SinglyLinkedList.hpp

listTestApp: listTestApp.cpp $(HEADER)
	g++ -o listTestApp listTestApp.cpp

listADT: listADT.cpp $(HEADER)
	g++ -o listADT listADT.cpp
